name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Download Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
                go install github.com/onsi/ginkgo/ginkgo@master
    - name: Get two dependencies
      run: |
                go install github.com/onsi/gomega/...@master 

    - name: Get three dependencies
      run: |
                go install gopkg.in/yaml@v3              
