name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Download Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go

    - name: Get three dependencies
      run: |
                go get -v gopkg.in/yaml.v2
    - name: Get two dependencies
      run: |
                go get -v github.com/onsi/ginkgo/ginkgo               
